### ISSUE TITLE
Drag doesn't stop when mouseup doesn't occur over object

### ISSUE THREAD

**Issue by kasparsz** [vladakilov/imagine#2] opened 2014-05-07 16:59 UTC
To repeat:
- http://codepen.io/anon/pen/lJFog
- start dragging text
- mouseup

Result: Drag is not stopped
Expected: Drag stops

**Comment by vladakilov** [comment] 2014-05-07 17:58
@kasparsz, I tried this in the codepen demo, I'm using Chrome and can't reproduce the bug. What browser are you using?

**Comment by kasparsz** [comment] 2014-05-07 20:25
Sorry, wrong demo, please see http://codepen.io/anon/pen/gqEAI

I'm using Chrome, but looked through source and it should affect all browsers.
Problem is that objects size changes and on mouse up cursor isn't over any object, so dragend doesn't happen.

**Comment by vladakilov** [comment] 2014-05-07 20:29
Nice catch. I'll push a fix for this soon.

**Closed as completed** 2014-05-08 01:36 UTC
Labels: bug
